import { Schema, Type } from '@google/genai';

export const getDiaryGenerationConfig = (keywords: string, level: 'beginner' | 'advanced' = 'advanced') => {
    const schema: Schema = {
        type: Type.OBJECT,
        properties: {
            sentences: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        english: {
                            type: Type.STRING,
                            description: "A single sentence of the diary entry in English.",
                        },
                        korean: {
                            type: Type.STRING,
                            description: "The Korean translation of the English sentence.",
                        },
                    },
                    required: ["english", "korean"],
                },
            },
        },
        required: ['sentences'],
    };

    let prompt = '';

    if (level === 'beginner') {
        prompt = `You are a helpful British English tutor. Your goal is to help a user write a diary entry in very simple, easy-to-understand British English (CEFR Level A1-A2).

Here are the user's keywords for the day: "${keywords}"

Your task is to:
1.  **Write a simple British English diary entry (5-7 sentences):**
    *   **Focus on Simplicity:** Use basic vocabulary and short, clear sentences that a beginner can easily understand.
    *   **Tone:** Keep it natural and polite, but not childish. It should sound like a normal daily log.
    *   **British English:** Use British spelling (e.g., 'colour', 'favourite', 'centre') and simple British terms (e.g., 'holiday', 'flat') where appropriate.
    *   Avoid complex grammar structures (like passive voice or complex relative clauses).

2.  **Provide a natural Korean translation** for each sentence, using polite language (e.g., 해요체).

Return the result as a JSON object containing an array of sentence pairs.`;
    } else {
        prompt = `You are a warm, sophisticated British English writing coach. Your goal is to help a user transform their daily keywords into a beautiful, natural-sounding diary entry in British English. The user is an English learner aiming for a mature, native-like style.

Here are the user's keywords for the day: "${keywords}"

Your task is to:
1.  **Write a British English diary entry (7-10 sentences):**
    *   Weave the keywords into a coherent and engaging narrative.
    *   **Crucial:** Use British spelling (e.g., 'colour', 'realise', 'centre') and vocabulary (e.g., 'flat', 'lift', 'biscuit', 'holiday').
    *   Use rich but accessible vocabulary and varied sentence structures.
    *   The tone should be reflective, personal, and slightly witty if appropriate.

2.  **Provide a natural Korean translation** for each sentence.

Return the result as a JSON object containing an array of sentence pairs.`;
    }

    return { schema, prompt };
};

export const getGrammarCheckConfig = (sentence: string) => {
    const schema: Schema = {
        type: Type.OBJECT,
        properties: {
            isCorrect: {
                type: Type.BOOLEAN,
                description: "Is the sentence grammatically correct?",
            },
            feedback: {
                type: Type.STRING,
                description: "A detailed commentary in Korean, but teaching British English concepts. If incorrect, explain the error in Korean. If correct, praise specific British features in Korean and suggest a 'level-up' sophisticated alternative phrasing.",
            },
            correctedSentence: {
                type: Type.STRING,
                description: "If incorrect, provide the corrected sentence. If correct, return the original sentence.",
            },
        },
        required: ['isCorrect', 'feedback', 'correctedSentence'],
    };

    const prompt = `You are a sophisticated and encouraging British English teacher. Your student is a Korean speaker learning British English.
Your task is to provide a "Deep Dive" analysis of the following sentence.

Sentence: "${sentence}"

Since this sentence was likely generated by an AI written in British English, it is probably grammatically correct.
**Your Main Goal is NOT just to find errors, but to TEACH and ELEVATE.**

1.  **If the sentence is correct**:
    *   **isCorrect**: true
    *   **feedback**: Praise specific British elements (e.g., "Splendid use of 'pavement'!"). **Crucially, offer a variation.** "To sound even more like a Londoner, you might also say: '[Alternative Refined Sentence]'."
    *   **correctedSentence**: The original sentence (since it's correct).

2.  **If the sentence has errors**:
    *   **isCorrect**: false
    *   **feedback**: Explain the error politely in a British manner.
    *   **correctedSentence**: The corrected version.

Return in JSON format only.

**IMPORTANT:** The \`feedback\` field MUST be written in **Korean** (한국어). The \`correctedSentence\` remains in English.

Example Feedback (Korean): "문법적으로 완벽합니다! 특히 'flat'이라는 단어를 사용해서 영국적인 느낌을 잘 살렸네요. 만약 조금 더 격식 있게 표현하고 싶다면 이렇게 말해볼 수도 있어요..."`;

    return { schema, prompt };
};
